btn1 = document.getElementById("but1");
btn2 = document.getElementById("but2");
btn3 = document.getElementById("but3");
btn4 = document.getElementById("but4");
btn5 = document.getElementById("but5");
btn6 = document.getElementById("but6");
btn7 = document.getElementById("but7");
btn8 = document.getElementById("but8");
btn9 = document.getElementById("but9");
btn10 = document.getElementById("but10");
btn11 = document.getElementById("but11");
btn12 = document.getElementById("but12");
btn13 = document.getElementById("but13");
btn14 = document.getElementById("but14");
btn15 = document.getElementById("but15");
btn16 = document.getElementById("but16");
btn17 = document.getElementById("but17");
btn18 = document.getElementById("but18");
btn19 = document.getElementById("but19");
btn20 = document.getElementById("but20");
btn21 = document.getElementById("but21");
btn22 = document.getElementById("but22");
btn23 = document.getElementById("but23");
btn24 = document.getElementById("but24");
btn25 = document.getElementById("but25");
btn26 = document.getElementById("but26");
btn27 = document.getElementById("but27");
btn28 = document.getElementById("but28");
btn29 = document.getElementById("but29");
btn30 = document.getElementById("but30");
btn31 = document.getElementById("but31");
btn32 = document.getElementById("but32");
btn33 = document.getElementById("but33");
btn34 = document.getElementById("but34");
btn35 = document.getElementById("but35");
btn36 = document.getElementById("but36");
btn37 = document.getElementById("but37");
btn38 = document.getElementById("but38");
btn39 = document.getElementById("but39");
btn40 = document.getElementById("but40");
btn41 = document.getElementById("but41");
btn42 = document.getElementById("but42");
btn43 = document.getElementById("but43");
btn44 = document.getElementById("but44");
btn45 = document.getElementById("but45");
btn46 = document.getElementById("but46");
btn47 = document.getElementById("but47");
btn48 = document.getElementById("but48");
btn49 = document.getElementById("but49");
btn50 = document.getElementById("but50");
btn51 = document.getElementById("but51");
btn52 = document.getElementById("but52");
btn53 = document.getElementById("but53");
btn54 = document.getElementById("but54");
btn55 = document.getElementById("but55");
btn56 = document.getElementById("but56");
btn57 = document.getElementById("but57");
btn58 = document.getElementById("but58");
btn59 = document.getElementById("but59");
btn60 = document.getElementById("but60");
btn61 = document.getElementById("but61");
btn62 = document.getElementById("but62");
btn63 = document.getElementById("but63");
btn64 = document.getElementById("but64");
btn65 = document.getElementById("but65");
btn66 = document.getElementById("but66");
btn67 = document.getElementById("but67");
btn68 = document.getElementById("but68");
btn69 = document.getElementById("but69");
btn70 = document.getElementById("but70");
btn71 = document.getElementById("but71");
btn72 = document.getElementById("but72");
btn73 = document.getElementById("but73");
btn74 = document.getElementById("but74");
btn75 = document.getElementById("but75");
btn76 = document.getElementById("but76");
btn77 = document.getElementById("but77");
btn78 = document.getElementById("but78");
btn79 = document.getElementById("but79");
btn80 = document.getElementById("but80");
btn81 = document.getElementById("but81");
btn82 = document.getElementById("but82");
btn83 = document.getElementById("but83");
btn84 = document.getElementById("but84");
btn85 = document.getElementById("but85");
btn86 = document.getElementById("but86");
btn87 = document.getElementById("but87");
btn88 = document.getElementById("but88");
btn89 = document.getElementById("but89");
btn90 = document.getElementById("but90");
btn91 = document.getElementById("but91");
btn92 = document.getElementById("but92");
btn93 = document.getElementById("but93");
btn94 = document.getElementById("but94");
btn95 = document.getElementById("but95");
btn96 = document.getElementById("but96");
btn97 = document.getElementById("but97");
btn98 = document.getElementById("but98");
btn99 = document.getElementById("but99");
btn100 = document.getElementById("but100");
btn101 = document.getElementById("but101");
btn102 = document.getElementById("but102");
btn103 = document.getElementById("but103");
btn104 = document.getElementById("but104");
btn105 = document.getElementById("but105");
btn106 = document.getElementById("but106");
btn107 = document.getElementById("but107");
btn108 = document.getElementById("but108");
btn109 = document.getElementById("but109");
btn110 = document.getElementById("but110");
btn111 = document.getElementById("but111");
btn112 = document.getElementById("but112");
btn113 = document.getElementById("but113");
btn114 = document.getElementById("but114");
btn115 = document.getElementById("but115");
btn116 = document.getElementById("but116");
btn117 = document.getElementById("but117");
btn118 = document.getElementById("but118");
btn119 = document.getElementById("but119");
btn120 = document.getElementById("but120");
btn121 = document.getElementById("but121");
btn122 = document.getElementById("but122");
btn123 = document.getElementById("but123");
btn124 = document.getElementById("but124");
btn125 = document.getElementById("but125");
btn126 = document.getElementById("but126");
btn127 = document.getElementById("but127");
btn128 = document.getElementById("but128");
btn129 = document.getElementById("but129");
btn130 = document.getElementById("but130");
btn131 = document.getElementById("but131");
btn132 = document.getElementById("but132");
btn133 = document.getElementById("but133");
btn134 = document.getElementById("but134");
btn135 = document.getElementById("but135");
btn136 = document.getElementById("but136");
btn137 = document.getElementById("but137");
btn138 = document.getElementById("but138");
btn139 = document.getElementById("but139");
btn140 = document.getElementById("but140");
btn141 = document.getElementById("but141");
btn142 = document.getElementById("but142");
btn143 = document.getElementById("but143");
btn144 = document.getElementById("but144");
btn145 = document.getElementById("but145");
btn146 = document.getElementById("but146");
btn147 = document.getElementById("but147");
btn148 = document.getElementById("but148");
btn149 = document.getElementById("but149");
btn150 = document.getElementById("but150");
btn151 = document.getElementById("but151");
btn152 = document.getElementById("but152");
btn153 = document.getElementById("but153");
btn154 = document.getElementById("but154");
btn155 = document.getElementById("but155");
btn156 = document.getElementById("but156");
btn157 = document.getElementById("but157");
btn158 = document.getElementById("but158");
btn159 = document.getElementById("but159");
btn160 = document.getElementById("but160");
btn161 = document.getElementById("but161");
btn162 = document.getElementById("but162");
btn163 = document.getElementById("but163");
btn164 = document.getElementById("but164");
btn165 = document.getElementById("but165");
btn166 = document.getElementById("but166");
btn167 = document.getElementById("but167");
btn168 = document.getElementById("but168");
btn169 = document.getElementById("but169");
btn170 = document.getElementById("but170");
btn171 = document.getElementById("but171");
btn172 = document.getElementById("but172");
btn173 = document.getElementById("but173");
btn174 = document.getElementById("but174");
btn175 = document.getElementById("but175");
btn176 = document.getElementById("but176");
btn177 = document.getElementById("but177");
btn178 = document.getElementById("but178");
btn179 = document.getElementById("but179");
btn180 = document.getElementById("but180");
btn181 = document.getElementById("but181");
btn182 = document.getElementById("but182");
btn183 = document.getElementById("but183");
btn184 = document.getElementById("but184");
btn185 = document.getElementById("but185");
btn186 = document.getElementById("but186");
btn187 = document.getElementById("but187");
btn188 = document.getElementById("but188");
btn189 = document.getElementById("but189");
btn190 = document.getElementById("but190");
btn191 = document.getElementById("but191");
btn192 = document.getElementById("but192");
btn193 = document.getElementById("but193");
btn194 = document.getElementById("but194");
btn195 = document.getElementById("but195");
btn196 = document.getElementById("but196");
btn197 = document.getElementById("but197");
btn198 = document.getElementById("but198");
btn199 = document.getElementById("but199");
btn200 = document.getElementById("but200");
btn201 = document.getElementById("but201");
btn202 = document.getElementById("but202");
btn203 = document.getElementById("but203");
btn204 = document.getElementById("but204");
btn205 = document.getElementById("but205");
btn206 = document.getElementById("but206");
btn207 = document.getElementById("but207");
btn208 = document.getElementById("but208");
btn209 = document.getElementById("but209");
btn210 = document.getElementById("but210");
btn211 = document.getElementById("but211");
btn212 = document.getElementById("but212");
btn213 = document.getElementById("but213");
btn214 = document.getElementById("but214");
btn215 = document.getElementById("but215");
btn216 = document.getElementById("but216");
btn217 = document.getElementById("but217");
btn218 = document.getElementById("but218");
btn219 = document.getElementById("but219");
btn220 = document.getElementById("but220");
btn221 = document.getElementById("but221");
btn222 = document.getElementById("but222");
btn223 = document.getElementById("but223");
btn224 = document.getElementById("but224");
btn225 = document.getElementById("but225");
btn226 = document.getElementById("but226");
btn227 = document.getElementById("but227");
btn228 = document.getElementById("but228");
btn229 = document.getElementById("but229");
btn230 = document.getElementById("but230");
btn231 = document.getElementById("but231");
btn232 = document.getElementById("but232");
btn233 = document.getElementById("but233");
btn234 = document.getElementById("but234");
btn235 = document.getElementById("but235");
btn236 = document.getElementById("but236");
btn237 = document.getElementById("but237");
btn238 = document.getElementById("but238");
btn239 = document.getElementById("but239");
btn240 = document.getElementById("but240");
btn241 = document.getElementById("but241");
btn242 = document.getElementById("but242");
btn243 = document.getElementById("but243");
btn244 = document.getElementById("but244");
btn245 = document.getElementById("but245");
btn246 = document.getElementById("but246");
btn247 = document.getElementById("but247");
btn248 = document.getElementById("but248");
btn249 = document.getElementById("but249");
btn250 = document.getElementById("but250");
btn251 = document.getElementById("but251");
btn252 = document.getElementById("but252");
btn253 = document.getElementById("but253");
btn254 = document.getElementById("but254");
btn255 = document.getElementById("but255");
btn256 = document.getElementById("but256");
btn257 = document.getElementById("but257");
btn258 = document.getElementById("but258");
btn259 = document.getElementById("but259");
btn260 = document.getElementById("but260");
btn261 = document.getElementById("but261");
btn262 = document.getElementById("but262");
btn263 = document.getElementById("but263");
btn264 = document.getElementById("but264");
btn265 = document.getElementById("but265");
btn266 = document.getElementById("but266");
btn267 = document.getElementById("but267");
btn268 = document.getElementById("but268");
btn269 = document.getElementById("but269");
btn270 = document.getElementById("but270");
btn271 = document.getElementById("but271");
btn272 = document.getElementById("but272");
btn273 = document.getElementById("but273");
btn274 = document.getElementById("but274");
btn275 = document.getElementById("but275");
btn276 = document.getElementById("but276");
btn277 = document.getElementById("but277");
btn278 = document.getElementById("but278");
btn279 = document.getElementById("but279");
btn280 = document.getElementById("but280");
btn281 = document.getElementById("but281");
btn282 = document.getElementById("but282");
btn283 = document.getElementById("but283");
btn284 = document.getElementById("but284");
btn285 = document.getElementById("but285");
btn286 = document.getElementById("but286");
btn287 = document.getElementById("but287");
btn288 = document.getElementById("but288");
btn289 = document.getElementById("but289");
btn290 = document.getElementById("but290");
btn291 = document.getElementById("but291");
btn292 = document.getElementById("but292");
btn293 = document.getElementById("but293");
btn294 = document.getElementById("but294");
btn295 = document.getElementById("but295");
btn296 = document.getElementById("but296");
btn297 = document.getElementById("but297");
btn298 = document.getElementById("but298");
btn299 = document.getElementById("but299");
btn300 = document.getElementById("but300");
btn301 = document.getElementById("but301");
btn302 = document.getElementById("but302");
btn303 = document.getElementById("but303");
btn304 = document.getElementById("but304");
btn305 = document.getElementById("but305");
btn306 = document.getElementById("but306");
btn307 = document.getElementById("but307");
btn308 = document.getElementById("but308");
btn309 = document.getElementById("but309");
btn310 = document.getElementById("but310");
btn311 = document.getElementById("but311");
btn312 = document.getElementById("but312");
btn313 = document.getElementById("but313");
btn314 = document.getElementById("but314");
btn315 = document.getElementById("but315");
btn316 = document.getElementById("but316");
btn317 = document.getElementById("but317");
btn318 = document.getElementById("but318");
btn319 = document.getElementById("but319");
btn320 = document.getElementById("but320");
btn321 = document.getElementById("but321");
btn322 = document.getElementById("but322");
btn323 = document.getElementById("but323");
btn324 = document.getElementById("but324");
btn325 = document.getElementById("but325");
btn326 = document.getElementById("but326");
btn327 = document.getElementById("but327");
btn328 = document.getElementById("but328");
btn329 = document.getElementById("but329");
btn330 = document.getElementById("but330");
btn331 = document.getElementById("but331");
btn332 = document.getElementById("but332");
btn333 = document.getElementById("but333");
btn334 = document.getElementById("but334");
btn335 = document.getElementById("but335");
btn336 = document.getElementById("but336");
btn337 = document.getElementById("but337");
btn338 = document.getElementById("but338");
btn339 = document.getElementById("but339");
btn340 = document.getElementById("but340");
btn341 = document.getElementById("but341");
btn342 = document.getElementById("but342");
btn343 = document.getElementById("but343");
btn344 = document.getElementById("but344");
btn345 = document.getElementById("but345");
btn346 = document.getElementById("but346");
btn347 = document.getElementById("but347");
btn348 = document.getElementById("but348");
btn349 = document.getElementById("but349");
btn350 = document.getElementById("but350");
btn351 = document.getElementById("but351");
btn352 = document.getElementById("but352");
btn353 = document.getElementById("but353");
btn354 = document.getElementById("but354");
btn355 = document.getElementById("but355");
btn356 = document.getElementById("but356");
btn357 = document.getElementById("but357");
btn358 = document.getElementById("but358");
btn359 = document.getElementById("but359");
btn360 = document.getElementById("but360");
btn361 = document.getElementById("but361");
btn362 = document.getElementById("but362");
btn363 = document.getElementById("but363");
btn364 = document.getElementById("but364");
btn365 = document.getElementById("but365");
btn366 = document.getElementById("but366");
btn367 = document.getElementById("but367");
btn368 = document.getElementById("but368");
btn369 = document.getElementById("but369");
btn370 = document.getElementById("but370");
btn371 = document.getElementById("but371");
btn372 = document.getElementById("but372");
btn373 = document.getElementById("but373");
btn374 = document.getElementById("but374");
btn375 = document.getElementById("but375");
btn376 = document.getElementById("but376");
btn377 = document.getElementById("but377");
btn378 = document.getElementById("but378");
btn379 = document.getElementById("but379");
btn380 = document.getElementById("but380");
btn381 = document.getElementById("but381");
btn382 = document.getElementById("but382");
btn383 = document.getElementById("but383");
btn384 = document.getElementById("but384");
btn385 = document.getElementById("but385");
btn386 = document.getElementById("but386");
btn387 = document.getElementById("but387");
btn388 = document.getElementById("but388");
btn389 = document.getElementById("but389");
btn390 = document.getElementById("but390");
btn391 = document.getElementById("but391");
btn392 = document.getElementById("but392");
btn393 = document.getElementById("but393");
btn394 = document.getElementById("but394");
btn395 = document.getElementById("but395");
btn396 = document.getElementById("but396");
btn397 = document.getElementById("but397");
btn398 = document.getElementById("but398");
btn399 = document.getElementById("but399");
btn400 = document.getElementById("but400");
btn401 = document.getElementById("but401");
btn402 = document.getElementById("but402");
btn403 = document.getElementById("but403");
btn404 = document.getElementById("but404");
btn405 = document.getElementById("but405");
btn406 = document.getElementById("but406");
btn407 = document.getElementById("but407");
btn408 = document.getElementById("but408");
btn409 = document.getElementById("but409");
btn410 = document.getElementById("but410");
btn411 = document.getElementById("but411");
btn412 = document.getElementById("but412");
btn413 = document.getElementById("but413");
btn414 = document.getElementById("but414");
btn415 = document.getElementById("but415");
btn416 = document.getElementById("but416");
btn417 = document.getElementById("but417");
btn418 = document.getElementById("but418");
btn419 = document.getElementById("but419");
btn420 = document.getElementById("but420");
btn421 = document.getElementById("but421");
btn422 = document.getElementById("but422");
btn423 = document.getElementById("but423");
btn424 = document.getElementById("but424");
btn425 = document.getElementById("but425");
btn426 = document.getElementById("but426");
btn427 = document.getElementById("but427");
btn428 = document.getElementById("but428");
btn429 = document.getElementById("but429");
btn430 = document.getElementById("but430");
btn431 = document.getElementById("but431");
btn432 = document.getElementById("but432");
btn433 = document.getElementById("but433");
btn434 = document.getElementById("but434");
btn435 = document.getElementById("but435");
btn436 = document.getElementById("but436");
btn437 = document.getElementById("but437");
btn438 = document.getElementById("but438");
btn439 = document.getElementById("but439");
btn440 = document.getElementById("but440");
btn441 = document.getElementById("but441");
btn442 = document.getElementById("but442");
btn443 = document.getElementById("but443");
btn444 = document.getElementById("but444");
btn445 = document.getElementById("but445");
btn446 = document.getElementById("but446");
btn447 = document.getElementById("but447");
btn448 = document.getElementById("but448");
btn449 = document.getElementById("but449");
btn450 = document.getElementById("but450");
btn451 = document.getElementById("but451");
btn452 = document.getElementById("but452");
btn453 = document.getElementById("but453");
btn454 = document.getElementById("but454");
btn455 = document.getElementById("but455");
btn456 = document.getElementById("but456");
btn457 = document.getElementById("but457");
btn458 = document.getElementById("but458");
btn459 = document.getElementById("but459");
btn460 = document.getElementById("but460");
btn461 = document.getElementById("but461");
btn462 = document.getElementById("but462");
btn463 = document.getElementById("but463");
btn464 = document.getElementById("but464");
btn465 = document.getElementById("but465");
btn466 = document.getElementById("but466");
btn467 = document.getElementById("but467");
btn468 = document.getElementById("but468");
btn469 = document.getElementById("but469");
btn470 = document.getElementById("but470");
btn471 = document.getElementById("but471");
btn472 = document.getElementById("but472");
btn473 = document.getElementById("but473");
btn474 = document.getElementById("but474");
btn475 = document.getElementById("but475");
btn476 = document.getElementById("but476");
btn477 = document.getElementById("but477");
btn478 = document.getElementById("but478");
btn479 = document.getElementById("but479");
btn480 = document.getElementById("but480");
btn481 = document.getElementById("but481");
btn482 = document.getElementById("but482");
btn483 = document.getElementById("but483");
btn484 = document.getElementById("but484");
btn485 = document.getElementById("but485");
btn486 = document.getElementById("but486");
btn487 = document.getElementById("but487");
btn488 = document.getElementById("but488");
btn489 = document.getElementById("but489");
btn490 = document.getElementById("but490");
btn491 = document.getElementById("but491");
btn492 = document.getElementById("but492");
btn493 = document.getElementById("but493");
btn494 = document.getElementById("but494");
btn495 = document.getElementById("but495");
btn496 = document.getElementById("but496");
btn497 = document.getElementById("but497");
btn498 = document.getElementById("but498");
btn499 = document.getElementById("but499");
btn500 = document.getElementById("but500");
btn501 = document.getElementById("but501");
btn502 = document.getElementById("but502");
btn503 = document.getElementById("but503");
btn504 = document.getElementById("but504");
btn505 = document.getElementById("but505");
btn506 = document.getElementById("but506");
btn507 = document.getElementById("but507");
btn508 = document.getElementById("but508");
btn509 = document.getElementById("but509");
btn510 = document.getElementById("but510");
btn511 = document.getElementById("but511");
btn512 = document.getElementById("but512");
btn513 = document.getElementById("but513");
btn514 = document.getElementById("but514");
btn515 = document.getElementById("but515");

btn1.setAttribute('onclick', 'pushButton1()');
btn2.setAttribute('onclick', 'pushButton1()');
btn3.setAttribute('onclick', 'pushButton1()');
btn4.setAttribute('onclick', 'pushButton1()');
btn5.setAttribute('onclick', 'pushButton1()');
btn6.setAttribute('onclick', 'pushButton1()');
btn7.setAttribute('onclick', 'pushButton1()');
btn8.setAttribute('onclick', 'pushButton1()');
btn9.setAttribute('onclick', 'pushButton1()');
btn10.setAttribute('onclick', 'pushButton1()');
btn11.setAttribute('onclick', 'pushButton1()');
btn12.setAttribute('onclick', 'pushButton1()');
btn13.setAttribute('onclick', 'pushButton1()');
btn14.setAttribute('onclick', 'pushButton1()');
btn15.setAttribute('onclick', 'pushButton1()');
btn16.setAttribute('onclick', 'pushButton1()');
btn17.setAttribute('onclick', 'pushButton1()');
btn18.setAttribute('onclick', 'pushButton1()');
btn19.setAttribute('onclick', 'pushButton1()');
btn20.setAttribute('onclick', 'pushButton1()');
btn21.setAttribute('onclick', 'pushButton1()');
btn22.setAttribute('onclick', 'pushButton1()');
btn23.setAttribute('onclick', 'pushButton1()');
btn24.setAttribute('onclick', 'pushButton1()');
btn25.setAttribute('onclick', 'pushButton1()');
btn26.setAttribute('onclick', 'pushButton1()');
btn27.setAttribute('onclick', 'pushButton1()');
btn28.setAttribute('onclick', 'pushButton1()');
btn29.setAttribute('onclick', 'pushButton1()');
btn30.setAttribute('onclick', 'pushButton1()');
btn31.setAttribute('onclick', 'pushButton1()');
btn32.setAttribute('onclick', 'pushButton1()');
btn33.setAttribute('onclick', 'pushButton1()');
btn34.setAttribute('onclick', 'pushButton1()');
btn35.setAttribute('onclick', 'pushButton1()');
btn36.setAttribute('onclick', 'pushButton1()');
btn37.setAttribute('onclick', 'pushButton1()');
btn38.setAttribute('onclick', 'pushButton1()');
btn39.setAttribute('onclick', 'pushButton1()');
btn40.setAttribute('onclick', 'pushButton1()');
btn41.setAttribute('onclick', 'pushButton1()');
btn42.setAttribute('onclick', 'pushButton1()');
btn43.setAttribute('onclick', 'pushButton1()');
btn44.setAttribute('onclick', 'pushButton1()');
btn45.setAttribute('onclick', 'pushButton1()');
btn46.setAttribute('onclick', 'pushButton1()');
btn47.setAttribute('onclick', 'pushButton1()');
btn48.setAttribute('onclick', 'pushButton1()');
btn49.setAttribute('onclick', 'pushButton1()');
btn50.setAttribute('onclick', 'pushButton1()');
btn51.setAttribute('onclick', 'pushButton1()');
btn52.setAttribute('onclick', 'pushButton1()');
btn53.setAttribute('onclick', 'pushButton1()');
btn54.setAttribute('onclick', 'pushButton1()');
btn55.setAttribute('onclick', 'pushButton1()');
btn56.setAttribute('onclick', 'pushButton1()');
btn57.setAttribute('onclick', 'pushButton1()');
btn58.setAttribute('onclick', 'pushButton1()');
btn59.setAttribute('onclick', 'pushButton1()');
btn60.setAttribute('onclick', 'pushButton1()');
btn61.setAttribute('onclick', 'pushButton1()');
btn62.setAttribute('onclick', 'pushButton1()');
btn63.setAttribute('onclick', 'pushButton1()');
btn64.setAttribute('onclick', 'pushButton1()');
btn65.setAttribute('onclick', 'pushButton1()');
btn66.setAttribute('onclick', 'pushButton1()');
btn67.setAttribute('onclick', 'pushButton1()');
btn68.setAttribute('onclick', 'pushButton1()');
btn69.setAttribute('onclick', 'pushButton1()');
btn70.setAttribute('onclick', 'pushButton1()');
btn71.setAttribute('onclick', 'pushButton1()');
btn72.setAttribute('onclick', 'pushButton1()');
btn73.setAttribute('onclick', 'pushButton1()');
btn74.setAttribute('onclick', 'pushButton1()');
btn75.setAttribute('onclick', 'pushButton1()');
btn76.setAttribute('onclick', 'pushButton1()');
btn77.setAttribute('onclick', 'pushButton1()');
btn78.setAttribute('onclick', 'pushButton1()');
btn79.setAttribute('onclick', 'pushButton1()');
btn80.setAttribute('onclick', 'pushButton1()');
btn81.setAttribute('onclick', 'pushButton1()');
btn82.setAttribute('onclick', 'pushButton1()');
btn83.setAttribute('onclick', 'pushButton1()');
btn84.setAttribute('onclick', 'pushButton1()');
btn85.setAttribute('onclick', 'pushButton1()');
btn86.setAttribute('onclick', 'pushButton1()');
btn87.setAttribute('onclick', 'pushButton1()');
btn88.setAttribute('onclick', 'pushButton1()');
btn89.setAttribute('onclick', 'pushButton1()');
btn90.setAttribute('onclick', 'pushButton1()');
btn91.setAttribute('onclick', 'pushButton1()');
btn92.setAttribute('onclick', 'pushButton1()');
btn93.setAttribute('onclick', 'pushButton1()');
btn94.setAttribute('onclick', 'pushButton1()');
btn95.setAttribute('onclick', 'pushButton1()');
btn96.setAttribute('onclick', 'pushButton1()');
btn97.setAttribute('onclick', 'pushButton1()');
btn98.setAttribute('onclick', 'pushButton1()');
btn99.setAttribute('onclick', 'pushButton1()');
btn100.setAttribute('onclick', 'pushButton1()');
btn101.setAttribute('onclick', 'pushButton1()');
btn102.setAttribute('onclick', 'pushButton1()');
btn103.setAttribute('onclick', 'pushButton1()');
btn104.setAttribute('onclick', 'pushButton1()');
btn105.setAttribute('onclick', 'pushButton1()');
btn106.setAttribute('onclick', 'pushButton1()');
btn107.setAttribute('onclick', 'pushButton1()');
btn108.setAttribute('onclick', 'pushButton1()');
btn109.setAttribute('onclick', 'pushButton1()');
btn110.setAttribute('onclick', 'pushButton1()');
btn111.setAttribute('onclick', 'pushButton1()');
btn112.setAttribute('onclick', 'pushButton1()');
btn113.setAttribute('onclick', 'pushButton1()');
btn114.setAttribute('onclick', 'pushButton1()');
btn115.setAttribute('onclick', 'pushButton1()');
btn116.setAttribute('onclick', 'pushButton1()');
btn117.setAttribute('onclick', 'pushButton1()');
btn118.setAttribute('onclick', 'pushButton1()');
btn119.setAttribute('onclick', 'pushButton1()');
btn120.setAttribute('onclick', 'pushButton1()');
btn121.setAttribute('onclick', 'pushButton1()');
btn122.setAttribute('onclick', 'pushButton1()');
btn123.setAttribute('onclick', 'pushButton1()');
btn124.setAttribute('onclick', 'pushButton1()');
btn125.setAttribute('onclick', 'pushButton1()');
btn126.setAttribute('onclick', 'pushButton1()');
btn127.setAttribute('onclick', 'pushButton1()');
btn128.setAttribute('onclick', 'pushButton1()');
btn129.setAttribute('onclick', 'pushButton1()');
btn130.setAttribute('onclick', 'pushButton1()');
btn131.setAttribute('onclick', 'pushButton1()');
btn132.setAttribute('onclick', 'pushButton1()');
btn133.setAttribute('onclick', 'pushButton1()');
btn134.setAttribute('onclick', 'pushButton1()');
btn135.setAttribute('onclick', 'pushButton1()');
btn136.setAttribute('onclick', 'pushButton1()');
btn137.setAttribute('onclick', 'pushButton1()');
btn138.setAttribute('onclick', 'pushButton1()');
btn139.setAttribute('onclick', 'pushButton1()');
btn140.setAttribute('onclick', 'pushButton1()');
btn141.setAttribute('onclick', 'pushButton1()');
btn142.setAttribute('onclick', 'pushButton1()');
btn143.setAttribute('onclick', 'pushButton1()');
btn144.setAttribute('onclick', 'pushButton1()');
btn145.setAttribute('onclick', 'pushButton1()');
btn146.setAttribute('onclick', 'pushButton1()');
btn147.setAttribute('onclick', 'pushButton1()');
btn148.setAttribute('onclick', 'pushButton1()');
btn149.setAttribute('onclick', 'pushButton1()');
btn150.setAttribute('onclick', 'pushButton1()');
btn151.setAttribute('onclick', 'pushButton1()');
btn152.setAttribute('onclick', 'pushButton1()');
btn153.setAttribute('onclick', 'pushButton1()');
btn154.setAttribute('onclick', 'pushButton1()');
btn155.setAttribute('onclick', 'pushButton1()');
btn156.setAttribute('onclick', 'pushButton1()');
btn157.setAttribute('onclick', 'pushButton1()');
btn158.setAttribute('onclick', 'pushButton1()');
btn159.setAttribute('onclick', 'pushButton1()');
btn160.setAttribute('onclick', 'pushButton1()');
btn161.setAttribute('onclick', 'pushButton1()');
btn162.setAttribute('onclick', 'pushButton1()');
btn163.setAttribute('onclick', 'pushButton1()');
btn164.setAttribute('onclick', 'pushButton1()');
btn165.setAttribute('onclick', 'pushButton1()');
btn166.setAttribute('onclick', 'pushButton1()');
btn167.setAttribute('onclick', 'pushButton1()');
btn168.setAttribute('onclick', 'pushButton1()');
btn169.setAttribute('onclick', 'pushButton1()');
btn170.setAttribute('onclick', 'pushButton1()');
btn171.setAttribute('onclick', 'pushButton1()');
btn172.setAttribute('onclick', 'pushButton1()');
btn173.setAttribute('onclick', 'pushButton1()');
btn174.setAttribute('onclick', 'pushButton1()');
btn175.setAttribute('onclick', 'pushButton1()');
btn176.setAttribute('onclick', 'pushButton1()');
btn177.setAttribute('onclick', 'pushButton1()');
btn178.setAttribute('onclick', 'pushButton1()');
btn179.setAttribute('onclick', 'pushButton1()');
btn180.setAttribute('onclick', 'pushButton1()');
btn181.setAttribute('onclick', 'pushButton1()');
btn182.setAttribute('onclick', 'pushButton1()');
btn183.setAttribute('onclick', 'pushButton1()');
btn184.setAttribute('onclick', 'pushButton1()');
btn185.setAttribute('onclick', 'pushButton1()');
btn186.setAttribute('onclick', 'pushButton1()');
btn187.setAttribute('onclick', 'pushButton1()');
btn188.setAttribute('onclick', 'pushButton1()');
btn189.setAttribute('onclick', 'pushButton1()');
btn190.setAttribute('onclick', 'pushButton1()');
btn191.setAttribute('onclick', 'pushButton1()');
btn192.setAttribute('onclick', 'pushButton1()');
btn193.setAttribute('onclick', 'pushButton1()');
btn194.setAttribute('onclick', 'pushButton1()');
btn195.setAttribute('onclick', 'pushButton1()');
btn196.setAttribute('onclick', 'pushButton1()');
btn197.setAttribute('onclick', 'pushButton1()');
btn198.setAttribute('onclick', 'pushButton1()');
btn199.setAttribute('onclick', 'pushButton1()');
btn200.setAttribute('onclick', 'pushButton1()');
btn201.setAttribute('onclick', 'pushButton1()');
btn202.setAttribute('onclick', 'pushButton1()');
btn203.setAttribute('onclick', 'pushButton1()');
btn204.setAttribute('onclick', 'pushButton1()');
btn205.setAttribute('onclick', 'pushButton1()');
btn206.setAttribute('onclick', 'pushButton1()');
btn207.setAttribute('onclick', 'pushButton1()');
btn208.setAttribute('onclick', 'pushButton1()');
btn209.setAttribute('onclick', 'pushButton1()');
btn210.setAttribute('onclick', 'pushButton1()');
btn211.setAttribute('onclick', 'pushButton1()');
btn212.setAttribute('onclick', 'pushButton1()');
btn213.setAttribute('onclick', 'pushButton1()');
btn214.setAttribute('onclick', 'pushButton1()');
btn215.setAttribute('onclick', 'pushButton1()');
btn216.setAttribute('onclick', 'pushButton1()');
btn217.setAttribute('onclick', 'pushButton1()');
btn218.setAttribute('onclick', 'pushButton1()');
btn219.setAttribute('onclick', 'pushButton1()');
btn220.setAttribute('onclick', 'pushButton1()');
btn221.setAttribute('onclick', 'pushButton1()');
btn222.setAttribute('onclick', 'pushButton1()');
btn223.setAttribute('onclick', 'pushButton1()');
btn224.setAttribute('onclick', 'pushButton1()');
btn225.setAttribute('onclick', 'pushButton1()');
btn226.setAttribute('onclick', 'pushButton1()');
btn227.setAttribute('onclick', 'pushButton1()');
btn228.setAttribute('onclick', 'pushButton1()');
btn229.setAttribute('onclick', 'pushButton1()');
btn230.setAttribute('onclick', 'pushButton1()');
btn231.setAttribute('onclick', 'pushButton1()');
btn232.setAttribute('onclick', 'pushButton1()');
btn233.setAttribute('onclick', 'pushButton1()');
btn234.setAttribute('onclick', 'pushButton1()');
btn235.setAttribute('onclick', 'pushButton1()');
btn236.setAttribute('onclick', 'pushButton1()');
btn237.setAttribute('onclick', 'pushButton1()');
btn238.setAttribute('onclick', 'pushButton1()');
btn239.setAttribute('onclick', 'pushButton1()');
btn240.setAttribute('onclick', 'pushButton1()');
btn241.setAttribute('onclick', 'pushButton1()');
btn242.setAttribute('onclick', 'pushButton1()');
btn243.setAttribute('onclick', 'pushButton1()');
btn244.setAttribute('onclick', 'pushButton1()');
btn245.setAttribute('onclick', 'pushButton1()');
btn246.setAttribute('onclick', 'pushButton1()');
btn247.setAttribute('onclick', 'pushButton1()');
btn248.setAttribute('onclick', 'pushButton1()');
btn249.setAttribute('onclick', 'pushButton1()');
btn250.setAttribute('onclick', 'pushButton1()');
btn251.setAttribute('onclick', 'pushButton1()');
btn252.setAttribute('onclick', 'pushButton1()');
btn253.setAttribute('onclick', 'pushButton1()');
btn254.setAttribute('onclick', 'pushButton1()');
btn255.setAttribute('onclick', 'pushButton1()');
btn256.setAttribute('onclick', 'pushButton1()');
btn257.setAttribute('onclick', 'pushButton1()');
btn258.setAttribute('onclick', 'pushButton1()');
btn259.setAttribute('onclick', 'pushButton1()');
btn260.setAttribute('onclick', 'pushButton1()');
btn261.setAttribute('onclick', 'pushButton1()');
btn262.setAttribute('onclick', 'pushButton1()');
btn263.setAttribute('onclick', 'pushButton1()');
btn264.setAttribute('onclick', 'pushButton1()');
btn265.setAttribute('onclick', 'pushButton1()');
btn266.setAttribute('onclick', 'pushButton1()');
btn267.setAttribute('onclick', 'pushButton1()');
btn268.setAttribute('onclick', 'pushButton1()');
btn269.setAttribute('onclick', 'pushButton1()');
btn270.setAttribute('onclick', 'pushButton1()');
btn271.setAttribute('onclick', 'pushButton1()');
btn272.setAttribute('onclick', 'pushButton1()');
btn273.setAttribute('onclick', 'pushButton1()');
btn274.setAttribute('onclick', 'pushButton1()');
btn275.setAttribute('onclick', 'pushButton1()');
btn276.setAttribute('onclick', 'pushButton1()');
btn277.setAttribute('onclick', 'pushButton1()');
btn278.setAttribute('onclick', 'pushButton1()');
btn279.setAttribute('onclick', 'pushButton1()');
btn280.setAttribute('onclick', 'pushButton1()');
btn281.setAttribute('onclick', 'pushButton1()');
btn282.setAttribute('onclick', 'pushButton1()');
btn283.setAttribute('onclick', 'pushButton1()');
btn284.setAttribute('onclick', 'pushButton1()');
btn285.setAttribute('onclick', 'pushButton1()');
btn286.setAttribute('onclick', 'pushButton1()');
btn287.setAttribute('onclick', 'pushButton1()');
btn288.setAttribute('onclick', 'pushButton1()');
btn289.setAttribute('onclick', 'pushButton1()');
btn290.setAttribute('onclick', 'pushButton1()');
btn291.setAttribute('onclick', 'pushButton1()');
btn292.setAttribute('onclick', 'pushButton1()');
btn293.setAttribute('onclick', 'pushButton1()');
btn294.setAttribute('onclick', 'pushButton1()');
btn295.setAttribute('onclick', 'pushButton1()');
btn296.setAttribute('onclick', 'pushButton1()');
btn297.setAttribute('onclick', 'pushButton1()');
btn298.setAttribute('onclick', 'pushButton1()');
btn299.setAttribute('onclick', 'pushButton1()');
btn300.setAttribute('onclick', 'pushButton1()');
btn301.setAttribute('onclick', 'pushButton1()');
btn302.setAttribute('onclick', 'pushButton1()');
btn303.setAttribute('onclick', 'pushButton1()');
btn304.setAttribute('onclick', 'pushButton1()');
btn305.setAttribute('onclick', 'pushButton1()');
btn306.setAttribute('onclick', 'pushButton1()');
btn307.setAttribute('onclick', 'pushButton1()');
btn308.setAttribute('onclick', 'pushButton1()');
btn309.setAttribute('onclick', 'pushButton1()');
btn310.setAttribute('onclick', 'pushButton1()');
btn311.setAttribute('onclick', 'pushButton1()');
btn312.setAttribute('onclick', 'pushButton1()');
btn313.setAttribute('onclick', 'pushButton1()');
btn314.setAttribute('onclick', 'pushButton1()');
btn315.setAttribute('onclick', 'pushButton1()');
btn316.setAttribute('onclick', 'pushButton1()');
btn317.setAttribute('onclick', 'pushButton1()');
btn318.setAttribute('onclick', 'pushButton1()');
btn319.setAttribute('onclick', 'pushButton1()');
btn320.setAttribute('onclick', 'pushButton1()');
btn321.setAttribute('onclick', 'pushButton1()');
btn322.setAttribute('onclick', 'pushButton1()');
btn323.setAttribute('onclick', 'pushButton1()');
btn324.setAttribute('onclick', 'pushButton1()');
btn325.setAttribute('onclick', 'pushButton1()');
btn326.setAttribute('onclick', 'pushButton1()');
btn327.setAttribute('onclick', 'pushButton1()');
btn328.setAttribute('onclick', 'pushButton1()');
btn329.setAttribute('onclick', 'pushButton1()');
btn330.setAttribute('onclick', 'pushButton1()');
btn331.setAttribute('onclick', 'pushButton1()');
btn332.setAttribute('onclick', 'pushButton1()');
btn333.setAttribute('onclick', 'pushButton1()');
btn334.setAttribute('onclick', 'pushButton1()');
btn335.setAttribute('onclick', 'pushButton1()');
btn336.setAttribute('onclick', 'pushButton1()');
btn337.setAttribute('onclick', 'pushButton1()');
btn338.setAttribute('onclick', 'pushButton1()');
btn339.setAttribute('onclick', 'pushButton1()');
btn340.setAttribute('onclick', 'pushButton1()');
btn341.setAttribute('onclick', 'pushButton1()');
btn342.setAttribute('onclick', 'pushButton1()');
btn343.setAttribute('onclick', 'pushButton1()');
btn344.setAttribute('onclick', 'pushButton1()');
btn345.setAttribute('onclick', 'pushButton1()');
btn346.setAttribute('onclick', 'pushButton1()');
btn347.setAttribute('onclick', 'pushButton1()');
btn348.setAttribute('onclick', 'pushButton1()');
btn349.setAttribute('onclick', 'pushButton1()');
btn350.setAttribute('onclick', 'pushButton1()');
btn351.setAttribute('onclick', 'pushButton1()');
btn352.setAttribute('onclick', 'pushButton1()');
btn353.setAttribute('onclick', 'pushButton1()');
btn354.setAttribute('onclick', 'pushButton1()');
btn355.setAttribute('onclick', 'pushButton1()');
btn356.setAttribute('onclick', 'pushButton1()');
btn357.setAttribute('onclick', 'pushButton1()');
btn358.setAttribute('onclick', 'pushButton1()');
btn359.setAttribute('onclick', 'pushButton1()');
btn360.setAttribute('onclick', 'pushButton1()');
btn361.setAttribute('onclick', 'pushButton1()');
btn362.setAttribute('onclick', 'pushButton1()');
btn363.setAttribute('onclick', 'pushButton1()');
btn364.setAttribute('onclick', 'pushButton1()');
btn365.setAttribute('onclick', 'pushButton1()');
btn366.setAttribute('onclick', 'pushButton1()');
btn367.setAttribute('onclick', 'pushButton1()');
btn368.setAttribute('onclick', 'pushButton1()');
btn369.setAttribute('onclick', 'pushButton1()');
btn370.setAttribute('onclick', 'pushButton1()');
btn371.setAttribute('onclick', 'pushButton1()');
btn372.setAttribute('onclick', 'pushButton1()');
btn373.setAttribute('onclick', 'pushButton1()');
btn374.setAttribute('onclick', 'pushButton1()');
btn375.setAttribute('onclick', 'pushButton1()');
btn376.setAttribute('onclick', 'pushButton1()');
btn377.setAttribute('onclick', 'pushButton1()');
btn378.setAttribute('onclick', 'pushButton1()');
btn379.setAttribute('onclick', 'pushButton1()');
btn380.setAttribute('onclick', 'pushButton1()');
btn381.setAttribute('onclick', 'pushButton1()');
btn382.setAttribute('onclick', 'pushButton1()');
btn383.setAttribute('onclick', 'pushButton1()');
btn384.setAttribute('onclick', 'pushButton1()');
btn385.setAttribute('onclick', 'pushButton1()');
btn386.setAttribute('onclick', 'pushButton1()');
btn387.setAttribute('onclick', 'pushButton1()');
btn388.setAttribute('onclick', 'pushButton1()');
btn389.setAttribute('onclick', 'pushButton1()');
btn390.setAttribute('onclick', 'pushButton1()');
btn391.setAttribute('onclick', 'pushButton1()');
btn392.setAttribute('onclick', 'pushButton1()');
btn393.setAttribute('onclick', 'pushButton1()');
btn394.setAttribute('onclick', 'pushButton1()');
btn395.setAttribute('onclick', 'pushButton1()');
btn396.setAttribute('onclick', 'pushButton1()');
btn397.setAttribute('onclick', 'pushButton1()');
btn398.setAttribute('onclick', 'pushButton1()');
btn399.setAttribute('onclick', 'pushButton1()');
btn400.setAttribute('onclick', 'pushButton1()');
btn401.setAttribute('onclick', 'pushButton1()');
btn402.setAttribute('onclick', 'pushButton1()');
btn403.setAttribute('onclick', 'pushButton1()');
btn404.setAttribute('onclick', 'pushButton1()');
btn405.setAttribute('onclick', 'pushButton1()');
btn406.setAttribute('onclick', 'pushButton1()');
btn407.setAttribute('onclick', 'pushButton1()');
btn408.setAttribute('onclick', 'pushButton1()');
btn409.setAttribute('onclick', 'pushButton1()');
btn410.setAttribute('onclick', 'pushButton1()');
btn411.setAttribute('onclick', 'pushButton1()');
btn412.setAttribute('onclick', 'pushButton1()');
btn413.setAttribute('onclick', 'pushButton1()');
btn414.setAttribute('onclick', 'pushButton1()');
btn415.setAttribute('onclick', 'pushButton1()');
btn416.setAttribute('onclick', 'pushButton1()');
btn417.setAttribute('onclick', 'pushButton1()');
btn418.setAttribute('onclick', 'pushButton1()');
btn419.setAttribute('onclick', 'pushButton1()');
btn420.setAttribute('onclick', 'pushButton1()');
btn421.setAttribute('onclick', 'pushButton1()');
btn422.setAttribute('onclick', 'pushButton1()');
btn423.setAttribute('onclick', 'pushButton1()');
btn424.setAttribute('onclick', 'pushButton1()');
btn425.setAttribute('onclick', 'pushButton1()');
btn426.setAttribute('onclick', 'pushButton1()');
btn427.setAttribute('onclick', 'pushButton1()');
btn428.setAttribute('onclick', 'pushButton1()');
btn429.setAttribute('onclick', 'pushButton1()');
btn430.setAttribute('onclick', 'pushButton1()');
btn431.setAttribute('onclick', 'pushButton1()');
btn432.setAttribute('onclick', 'pushButton1()');
btn433.setAttribute('onclick', 'pushButton1()');
btn434.setAttribute('onclick', 'pushButton1()');
btn435.setAttribute('onclick', 'pushButton1()');
btn436.setAttribute('onclick', 'pushButton1()');
btn437.setAttribute('onclick', 'pushButton1()');
btn438.setAttribute('onclick', 'pushButton1()');
btn439.setAttribute('onclick', 'pushButton1()');
btn440.setAttribute('onclick', 'pushButton1()');
btn441.setAttribute('onclick', 'pushButton1()');
btn442.setAttribute('onclick', 'pushButton1()');
btn443.setAttribute('onclick', 'pushButton1()');
btn444.setAttribute('onclick', 'pushButton1()');
btn445.setAttribute('onclick', 'pushButton1()');
btn446.setAttribute('onclick', 'pushButton1()');
btn447.setAttribute('onclick', 'pushButton1()');
btn448.setAttribute('onclick', 'pushButton1()');
btn449.setAttribute('onclick', 'pushButton1()');
btn450.setAttribute('onclick', 'pushButton1()');
btn451.setAttribute('onclick', 'pushButton1()');
btn452.setAttribute('onclick', 'pushButton1()');
btn453.setAttribute('onclick', 'pushButton1()');
btn454.setAttribute('onclick', 'pushButton1()');
btn455.setAttribute('onclick', 'pushButton1()');
btn456.setAttribute('onclick', 'pushButton1()');
btn457.setAttribute('onclick', 'pushButton1()');
btn458.setAttribute('onclick', 'pushButton1()');
btn459.setAttribute('onclick', 'pushButton1()');
btn460.setAttribute('onclick', 'pushButton1()');
btn461.setAttribute('onclick', 'pushButton1()');
btn462.setAttribute('onclick', 'pushButton1()');
btn463.setAttribute('onclick', 'pushButton1()');
btn464.setAttribute('onclick', 'pushButton1()');
btn465.setAttribute('onclick', 'pushButton1()');
btn466.setAttribute('onclick', 'pushButton1()');
btn467.setAttribute('onclick', 'pushButton1()');
btn468.setAttribute('onclick', 'pushButton1()');
btn469.setAttribute('onclick', 'pushButton1()');
btn470.setAttribute('onclick', 'pushButton1()');
btn471.setAttribute('onclick', 'pushButton1()');
btn472.setAttribute('onclick', 'pushButton1()');
btn473.setAttribute('onclick', 'pushButton1()');
btn474.setAttribute('onclick', 'pushButton1()');
btn475.setAttribute('onclick', 'pushButton1()');
btn476.setAttribute('onclick', 'pushButton1()');
btn477.setAttribute('onclick', 'pushButton1()');
btn478.setAttribute('onclick', 'pushButton1()');
btn479.setAttribute('onclick', 'pushButton1()');
btn480.setAttribute('onclick', 'pushButton1()');
btn481.setAttribute('onclick', 'pushButton1()');
btn482.setAttribute('onclick', 'pushButton1()');
btn483.setAttribute('onclick', 'pushButton1()');
btn484.setAttribute('onclick', 'pushButton1()');
btn485.setAttribute('onclick', 'pushButton1()');
btn486.setAttribute('onclick', 'pushButton1()');
btn487.setAttribute('onclick', 'pushButton1()');
btn488.setAttribute('onclick', 'pushButton1()');
btn489.setAttribute('onclick', 'pushButton1()');
btn490.setAttribute('onclick', 'pushButton1()');
btn491.setAttribute('onclick', 'pushButton1()');
btn492.setAttribute('onclick', 'pushButton1()');
btn493.setAttribute('onclick', 'pushButton1()');
btn494.setAttribute('onclick', 'pushButton1()');
btn495.setAttribute('onclick', 'pushButton1()');
btn496.setAttribute('onclick', 'pushButton1()');
btn497.setAttribute('onclick', 'pushButton1()');
btn498.setAttribute('onclick', 'pushButton1()');
btn499.setAttribute('onclick', 'pushButton1()');
btn500.setAttribute('onclick', 'pushButton1()');
btn501.setAttribute('onclick', 'pushButton1()');
btn502.setAttribute('onclick', 'pushButton1()');
btn503.setAttribute('onclick', 'pushButton1()');
btn504.setAttribute('onclick', 'pushButton1()');
btn505.setAttribute('onclick', 'pushButton1()');
btn506.setAttribute('onclick', 'pushButton1()');
btn507.setAttribute('onclick', 'pushButton1()');
btn508.setAttribute('onclick', 'pushButton1()');
btn509.setAttribute('onclick', 'pushButton1()');
btn510.setAttribute('onclick', 'pushButton1()');
btn511.setAttribute('onclick', 'pushButton1()');
btn512.setAttribute('onclick', 'pushButton1()');
btn513.setAttribute('onclick', 'pushButton1()');
btn514.setAttribute('onclick', 'pushButton1()');
btn515.setAttribute('onclick', 'pushButton1()');

function pushButton1(clicked_id) {
    bun_num = clicked_id
    let tit = document.getElementById(bun_num);
    let p_title = tit.title;
    let p_url = tit.src;
    let p_id = p_url.replace('http://drive.google.com/uc?export=view&id=',"")
    console.log(p_title,p_id);
    let resurl=(`http://localhost:8501/?&userid=aaaa&displayname=bbbb&p_id=${p_id}&p_title=${p_title}`)
    location.href=resurl
    
    liff.sendMessages([{
        'type': 'text',
        'text': p_title + "の注文をリクエストしました。"
      }]).then(function() {
        // document.getElementById('log').value += 'sendMessagesText completed\n';
      }).catch(function(error) {
        // document.getElementById('log').value += 'sendMessagesText()=' + error + '\n';
      });
      
    };
